// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic_svr.proto

package basic_svr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMD int32

const (
	CMD_SIGNUP_CMD            CMD = 1
	CMD_GETONLINEUSERLIST_CMD CMD = 2
	CMD_SENDMSG_CMD           CMD = 3
)

var CMD_name = map[int32]string{
	1: "SIGNUP_CMD",
	2: "GETONLINEUSERLIST_CMD",
	3: "SENDMSG_CMD",
}

var CMD_value = map[string]int32{
	"SIGNUP_CMD":            1,
	"GETONLINEUSERLIST_CMD": 2,
	"SENDMSG_CMD":           3,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}

func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}

func (CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{0}
}

//用户信息
type UserInfo struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nick                 *string  `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UserInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

//======================================================0x1 注册
type SignUpReq struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type SignUpRsp struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{2}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//======================================================0x3 获取在线人员列表
type GetOnlineUserListReq struct {
	Begin                *uint32  `protobuf:"varint,1,opt,name=begin" json:"begin,omitempty"`
	Count                *uint32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineUserListReq) Reset()         { *m = GetOnlineUserListReq{} }
func (m *GetOnlineUserListReq) String() string { return proto.CompactTextString(m) }
func (*GetOnlineUserListReq) ProtoMessage()    {}
func (*GetOnlineUserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{3}
}

func (m *GetOnlineUserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineUserListReq.Unmarshal(m, b)
}
func (m *GetOnlineUserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineUserListReq.Marshal(b, m, deterministic)
}
func (m *GetOnlineUserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineUserListReq.Merge(m, src)
}
func (m *GetOnlineUserListReq) XXX_Size() int {
	return xxx_messageInfo_GetOnlineUserListReq.Size(m)
}
func (m *GetOnlineUserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineUserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineUserListReq proto.InternalMessageInfo

func (m *GetOnlineUserListReq) GetBegin() uint32 {
	if m != nil && m.Begin != nil {
		return *m.Begin
	}
	return 0
}

func (m *GetOnlineUserListReq) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type GetOnlineUserListRsp struct {
	UserList             []*UserInfo `protobuf:"bytes,1,rep,name=user_list,json=userList" json:"user_list,omitempty"`
	IsEnd                *uint32     `protobuf:"varint,2,opt,name=is_end,json=isEnd" json:"is_end,omitempty"`
	Result               *uint32     `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetOnlineUserListRsp) Reset()         { *m = GetOnlineUserListRsp{} }
func (m *GetOnlineUserListRsp) String() string { return proto.CompactTextString(m) }
func (*GetOnlineUserListRsp) ProtoMessage()    {}
func (*GetOnlineUserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{4}
}

func (m *GetOnlineUserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineUserListRsp.Unmarshal(m, b)
}
func (m *GetOnlineUserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineUserListRsp.Marshal(b, m, deterministic)
}
func (m *GetOnlineUserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineUserListRsp.Merge(m, src)
}
func (m *GetOnlineUserListRsp) XXX_Size() int {
	return xxx_messageInfo_GetOnlineUserListRsp.Size(m)
}
func (m *GetOnlineUserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineUserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineUserListRsp proto.InternalMessageInfo

func (m *GetOnlineUserListRsp) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GetOnlineUserListRsp) GetIsEnd() uint32 {
	if m != nil && m.IsEnd != nil {
		return *m.IsEnd
	}
	return 0
}

func (m *GetOnlineUserListRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//======================================================0x3 发送信息请求
type SendMsgReq struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{5}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SendMsgReq) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type SendMsgRsp struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgRsp) Reset()         { *m = SendMsgRsp{} }
func (m *SendMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SendMsgRsp) ProtoMessage()    {}
func (*SendMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f434226aee82d3ba, []int{6}
}

func (m *SendMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRsp.Unmarshal(m, b)
}
func (m *SendMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRsp.Marshal(b, m, deterministic)
}
func (m *SendMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRsp.Merge(m, src)
}
func (m *SendMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SendMsgRsp.Size(m)
}
func (m *SendMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRsp proto.InternalMessageInfo

func (m *SendMsgRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("basic_svr.CMD", CMD_name, CMD_value)
	proto.RegisterType((*UserInfo)(nil), "basic_svr.UserInfo")
	proto.RegisterType((*SignUpReq)(nil), "basic_svr.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "basic_svr.SignUpRsp")
	proto.RegisterType((*GetOnlineUserListReq)(nil), "basic_svr.GetOnlineUserListReq")
	proto.RegisterType((*GetOnlineUserListRsp)(nil), "basic_svr.GetOnlineUserListRsp")
	proto.RegisterType((*SendMsgReq)(nil), "basic_svr.SendMsgReq")
	proto.RegisterType((*SendMsgRsp)(nil), "basic_svr.SendMsgRsp")
}

func init() { proto.RegisterFile("basic_svr.proto", fileDescriptor_f434226aee82d3ba) }

var fileDescriptor_f434226aee82d3ba = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x03, 0xd4, 0xa6, 0x4c, 0xd3, 0x3f, 0x59, 0x5b, 0x53, 0x6f, 0x0d, 0x7a, 0x68, 0x3c,
	0x10, 0xe3, 0xdd, 0x83, 0xb6, 0x84, 0x90, 0x14, 0x6a, 0x76, 0xcb, 0x99, 0xd8, 0xb2, 0x25, 0x1b,
	0xeb, 0x82, 0x0c, 0xe8, 0xd7, 0x37, 0x4b, 0x29, 0x55, 0xa3, 0xde, 0x66, 0x66, 0xf7, 0xbd, 0xf7,
	0xcb, 0x83, 0xc1, 0xe6, 0x19, 0xc5, 0x36, 0xc2, 0xf7, 0xdc, 0xce, 0xf2, 0xb4, 0x48, 0x89, 0xd9,
	0x1c, 0x2c, 0x1b, 0x3a, 0x21, 0xf2, 0xdc, 0x93, 0xbb, 0x94, 0xf4, 0x41, 0x17, 0xf1, 0x44, 0x9b,
	0x6a, 0xb3, 0x16, 0xd5, 0x45, 0x4c, 0x08, 0xb4, 0xa4, 0xd8, 0xbe, 0x4c, 0xf4, 0xa9, 0x36, 0x33,
	0x69, 0x35, 0x5b, 0xf7, 0x60, 0x32, 0x91, 0xc8, 0x30, 0xa3, 0xfc, 0x8d, 0xdc, 0x82, 0x59, 0x22,
	0xcf, 0x23, 0x21, 0x77, 0x69, 0xa5, 0xeb, 0xde, 0x9d, 0xdb, 0xa7, 0xb0, 0xa3, 0x31, 0xed, 0x94,
	0xf5, 0x64, 0x5d, 0x35, 0x72, 0xcc, 0xc8, 0x05, 0xb4, 0x73, 0x8e, 0xe5, 0xbe, 0xa8, 0xb4, 0x3d,
	0x5a, 0x6f, 0xd6, 0x23, 0x8c, 0x5c, 0x5e, 0xac, 0xe4, 0x5e, 0x48, 0xae, 0x3c, 0x96, 0x02, 0x0b,
	0x15, 0x37, 0x82, 0xb3, 0x0d, 0x4f, 0x84, 0xac, 0xbf, 0x1f, 0x16, 0x75, 0xdd, 0xa6, 0xa5, 0x2c,
	0x2a, 0xcc, 0x1e, 0x3d, 0x2c, 0xd6, 0xc7, 0x6f, 0x1e, 0x98, 0x35, 0xc8, 0x7b, 0x81, 0x2a, 0xd6,
	0xf8, 0x17, 0x59, 0x89, 0xc8, 0x18, 0xda, 0x02, 0x23, 0x2e, 0xe3, 0x63, 0x80, 0x40, 0x47, 0xc6,
	0x5f, 0xe0, 0x8d, 0x6f, 0xf0, 0x36, 0x00, 0xe3, 0x32, 0xf6, 0x31, 0x51, 0xc8, 0x3f, 0x2b, 0x1d,
	0x82, 0xf1, 0x8a, 0x49, 0xdd, 0xa8, 0x1a, 0xad, 0xeb, 0xd3, 0xff, 0xbf, 0x2b, 0xb9, 0x79, 0x00,
	0x63, 0xee, 0x2f, 0x48, 0x1f, 0x80, 0x79, 0x6e, 0x10, 0x3e, 0x45, 0x73, 0x7f, 0x31, 0xd4, 0xc8,
	0x25, 0x8c, 0x5d, 0x67, 0xbd, 0x0a, 0x96, 0x5e, 0xe0, 0x84, 0xcc, 0xa1, 0x4b, 0x8f, 0xad, 0xab,
	0x27, 0x9d, 0x0c, 0xa0, 0xcb, 0x9c, 0x60, 0xe1, 0x33, 0xb7, 0x3a, 0x18, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0xb0, 0x8a, 0x5f, 0x06, 0x02, 0x00, 0x00,
}
