// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: demogrpc.proto

#include "demogrpc.pb.h"
#include "demogrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace DemoGrpc {

static const char* DemoGrpcer_method_names[] = {
  "/DemoGrpc.DemoGrpcer/GetDemoRsp",
};

std::unique_ptr< DemoGrpcer::Stub> DemoGrpcer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DemoGrpcer::Stub> stub(new DemoGrpcer::Stub(channel));
  return stub;
}

DemoGrpcer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetDemoRsp_(DemoGrpcer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DemoGrpcer::Stub::GetDemoRsp(::grpc::ClientContext* context, const ::DemoGrpc::DemoReq& request, ::DemoGrpc::DemoRsp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetDemoRsp_, context, request, response);
}

void DemoGrpcer::Stub::experimental_async::GetDemoRsp(::grpc::ClientContext* context, const ::DemoGrpc::DemoReq* request, ::DemoGrpc::DemoRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDemoRsp_, context, request, response, std::move(f));
}

void DemoGrpcer::Stub::experimental_async::GetDemoRsp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::DemoGrpc::DemoRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDemoRsp_, context, request, response, std::move(f));
}

void DemoGrpcer::Stub::experimental_async::GetDemoRsp(::grpc::ClientContext* context, const ::DemoGrpc::DemoReq* request, ::DemoGrpc::DemoRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDemoRsp_, context, request, response, reactor);
}

void DemoGrpcer::Stub::experimental_async::GetDemoRsp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::DemoGrpc::DemoRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDemoRsp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DemoGrpc::DemoRsp>* DemoGrpcer::Stub::AsyncGetDemoRspRaw(::grpc::ClientContext* context, const ::DemoGrpc::DemoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::DemoGrpc::DemoRsp>::Create(channel_.get(), cq, rpcmethod_GetDemoRsp_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::DemoGrpc::DemoRsp>* DemoGrpcer::Stub::PrepareAsyncGetDemoRspRaw(::grpc::ClientContext* context, const ::DemoGrpc::DemoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::DemoGrpc::DemoRsp>::Create(channel_.get(), cq, rpcmethod_GetDemoRsp_, context, request, false);
}

DemoGrpcer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DemoGrpcer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DemoGrpcer::Service, ::DemoGrpc::DemoReq, ::DemoGrpc::DemoRsp>(
          std::mem_fn(&DemoGrpcer::Service::GetDemoRsp), this)));
}

DemoGrpcer::Service::~Service() {
}

::grpc::Status DemoGrpcer::Service::GetDemoRsp(::grpc::ServerContext* context, const ::DemoGrpc::DemoReq* request, ::DemoGrpc::DemoRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace DemoGrpc

