// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_client.proto

package chat_client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMD int32

const (
	CMD_SIGNUP_CMD            CMD = 1
	CMD_SIGNIN_CMD            CMD = 2
	CMD_GETONLINEUSERLIST_CMD CMD = 3
	CMD_SENDMSG_CMD           CMD = 4
)

var CMD_name = map[int32]string{
	1: "SIGNUP_CMD",
	2: "SIGNIN_CMD",
	3: "GETONLINEUSERLIST_CMD",
	4: "SENDMSG_CMD",
}

var CMD_value = map[string]int32{
	"SIGNUP_CMD":            1,
	"SIGNIN_CMD":            2,
	"GETONLINEUSERLIST_CMD": 3,
	"SENDMSG_CMD":           4,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}

func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}

func (CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{0}
}

type UserInfo struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nick                 *string  `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UserInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

//======================================================0x1
type SignUpReq struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type SignUpRsp struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{2}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//======================================================0x2
type SignInReq struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{3}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type SignInRsp struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRsp) Reset()         { *m = SignInRsp{} }
func (m *SignInRsp) String() string { return proto.CompactTextString(m) }
func (*SignInRsp) ProtoMessage()    {}
func (*SignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{4}
}

func (m *SignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRsp.Unmarshal(m, b)
}
func (m *SignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRsp.Marshal(b, m, deterministic)
}
func (m *SignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRsp.Merge(m, src)
}
func (m *SignInRsp) XXX_Size() int {
	return xxx_messageInfo_SignInRsp.Size(m)
}
func (m *SignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRsp proto.InternalMessageInfo

func (m *SignInRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//======================================================0x3
type GetOnlineUserListReq struct {
	Begin                *uint32  `protobuf:"varint,1,opt,name=begin" json:"begin,omitempty"`
	Count                *uint32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineUserListReq) Reset()         { *m = GetOnlineUserListReq{} }
func (m *GetOnlineUserListReq) String() string { return proto.CompactTextString(m) }
func (*GetOnlineUserListReq) ProtoMessage()    {}
func (*GetOnlineUserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{5}
}

func (m *GetOnlineUserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineUserListReq.Unmarshal(m, b)
}
func (m *GetOnlineUserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineUserListReq.Marshal(b, m, deterministic)
}
func (m *GetOnlineUserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineUserListReq.Merge(m, src)
}
func (m *GetOnlineUserListReq) XXX_Size() int {
	return xxx_messageInfo_GetOnlineUserListReq.Size(m)
}
func (m *GetOnlineUserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineUserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineUserListReq proto.InternalMessageInfo

func (m *GetOnlineUserListReq) GetBegin() uint32 {
	if m != nil && m.Begin != nil {
		return *m.Begin
	}
	return 0
}

func (m *GetOnlineUserListReq) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type GetOnlineUserListRsp struct {
	UserList             []*UserInfo `protobuf:"bytes,1,rep,name=user_list,json=userList" json:"user_list,omitempty"`
	CurrPos              *uint32     `protobuf:"varint,2,opt,name=curr_pos,json=currPos" json:"curr_pos,omitempty"`
	Result               *uint32     `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetOnlineUserListRsp) Reset()         { *m = GetOnlineUserListRsp{} }
func (m *GetOnlineUserListRsp) String() string { return proto.CompactTextString(m) }
func (*GetOnlineUserListRsp) ProtoMessage()    {}
func (*GetOnlineUserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{6}
}

func (m *GetOnlineUserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineUserListRsp.Unmarshal(m, b)
}
func (m *GetOnlineUserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineUserListRsp.Marshal(b, m, deterministic)
}
func (m *GetOnlineUserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineUserListRsp.Merge(m, src)
}
func (m *GetOnlineUserListRsp) XXX_Size() int {
	return xxx_messageInfo_GetOnlineUserListRsp.Size(m)
}
func (m *GetOnlineUserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineUserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineUserListRsp proto.InternalMessageInfo

func (m *GetOnlineUserListRsp) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GetOnlineUserListRsp) GetCurrPos() uint32 {
	if m != nil && m.CurrPos != nil {
		return *m.CurrPos
	}
	return 0
}

func (m *GetOnlineUserListRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//======================================================0x4
type SendMsgReq struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{7}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SendMsgReq) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type SendMsgRsp struct {
	Result               *uint32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgRsp) Reset()         { *m = SendMsgRsp{} }
func (m *SendMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SendMsgRsp) ProtoMessage()    {}
func (*SendMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{8}
}

func (m *SendMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRsp.Unmarshal(m, b)
}
func (m *SendMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRsp.Marshal(b, m, deterministic)
}
func (m *SendMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRsp.Merge(m, src)
}
func (m *SendMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SendMsgRsp.Size(m)
}
func (m *SendMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRsp proto.InternalMessageInfo

func (m *SendMsgRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

//============================================================>
type ChatMsgReq struct {
	Cmd                  *uint32  `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Ex                   []byte   `protobuf:"bytes,2,opt,name=ex" json:"ex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMsgReq) Reset()         { *m = ChatMsgReq{} }
func (m *ChatMsgReq) String() string { return proto.CompactTextString(m) }
func (*ChatMsgReq) ProtoMessage()    {}
func (*ChatMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{9}
}

func (m *ChatMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsgReq.Unmarshal(m, b)
}
func (m *ChatMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsgReq.Marshal(b, m, deterministic)
}
func (m *ChatMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsgReq.Merge(m, src)
}
func (m *ChatMsgReq) XXX_Size() int {
	return xxx_messageInfo_ChatMsgReq.Size(m)
}
func (m *ChatMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsgReq proto.InternalMessageInfo

func (m *ChatMsgReq) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *ChatMsgReq) GetEx() []byte {
	if m != nil {
		return m.Ex
	}
	return nil
}

type ChatMsgRsp struct {
	Cmd                  *uint32  `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Ex                   []byte   `protobuf:"bytes,2,opt,name=ex" json:"ex,omitempty"`
	Result               *uint32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMsgRsp) Reset()         { *m = ChatMsgRsp{} }
func (m *ChatMsgRsp) String() string { return proto.CompactTextString(m) }
func (*ChatMsgRsp) ProtoMessage()    {}
func (*ChatMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f033c3cf63e42ba, []int{10}
}

func (m *ChatMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsgRsp.Unmarshal(m, b)
}
func (m *ChatMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsgRsp.Marshal(b, m, deterministic)
}
func (m *ChatMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsgRsp.Merge(m, src)
}
func (m *ChatMsgRsp) XXX_Size() int {
	return xxx_messageInfo_ChatMsgRsp.Size(m)
}
func (m *ChatMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsgRsp proto.InternalMessageInfo

func (m *ChatMsgRsp) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *ChatMsgRsp) GetEx() []byte {
	if m != nil {
		return m.Ex
	}
	return nil
}

func (m *ChatMsgRsp) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("chat_client.CMD", CMD_name, CMD_value)
	proto.RegisterType((*UserInfo)(nil), "chat_client.UserInfo")
	proto.RegisterType((*SignUpReq)(nil), "chat_client.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "chat_client.SignUpRsp")
	proto.RegisterType((*SignInReq)(nil), "chat_client.SignInReq")
	proto.RegisterType((*SignInRsp)(nil), "chat_client.SignInRsp")
	proto.RegisterType((*GetOnlineUserListReq)(nil), "chat_client.GetOnlineUserListReq")
	proto.RegisterType((*GetOnlineUserListRsp)(nil), "chat_client.GetOnlineUserListRsp")
	proto.RegisterType((*SendMsgReq)(nil), "chat_client.SendMsgReq")
	proto.RegisterType((*SendMsgRsp)(nil), "chat_client.SendMsgRsp")
	proto.RegisterType((*ChatMsgReq)(nil), "chat_client.ChatMsgReq")
	proto.RegisterType((*ChatMsgRsp)(nil), "chat_client.ChatMsgRsp")
}

func init() { proto.RegisterFile("chat_client.proto", fileDescriptor_6f033c3cf63e42ba) }

var fileDescriptor_6f033c3cf63e42ba = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x55, 0x12, 0xda, 0xc2, 0x50, 0x28, 0xb5, 0xa0, 0x82, 0x1b, 0x4a, 0x7b, 0x40, 0x3d, 0xe4,
	0xc0, 0x1f, 0xa8, 0x54, 0x48, 0xa3, 0x48, 0x24, 0x50, 0x87, 0x9c, 0x23, 0x9a, 0x98, 0x60, 0x35,
	0x38, 0xd9, 0xd8, 0x91, 0xb8, 0xec, 0x7f, 0x5f, 0xd9, 0x84, 0x8f, 0x5d, 0xed, 0xc2, 0x61, 0x6f,
	0xef, 0x8d, 0xdf, 0xbc, 0x37, 0xe3, 0x81, 0xaf, 0xf1, 0x6e, 0x23, 0xa2, 0x38, 0xa3, 0x84, 0x09,
	0xab, 0x28, 0x73, 0x91, 0xa3, 0xf6, 0x55, 0xc9, 0xb4, 0xa0, 0x19, 0x72, 0x52, 0xba, 0x6c, 0x9b,
	0xa3, 0x2e, 0xe8, 0x34, 0x19, 0x6a, 0x63, 0x6d, 0xd2, 0xc0, 0x3a, 0x4d, 0x10, 0x82, 0x06, 0xa3,
	0xf1, 0xff, 0xa1, 0x3e, 0xd6, 0x26, 0x2d, 0xac, 0xb0, 0xf9, 0x0b, 0x5a, 0x01, 0x4d, 0x59, 0x58,
	0x60, 0xf2, 0x80, 0xa6, 0xd0, 0xaa, 0x38, 0x29, 0x23, 0xca, 0xb6, 0xb9, 0xea, 0x6b, 0x4f, 0x07,
	0xd6, 0x75, 0xe0, 0xc9, 0x1a, 0x37, 0xab, 0x1a, 0x99, 0xdf, 0xcf, 0x06, 0xbc, 0x40, 0xdf, 0xe0,
	0x63, 0x49, 0x78, 0x95, 0x09, 0xd5, 0xdd, 0xc1, 0x35, 0x3b, 0xa5, 0xb8, 0xec, 0x9d, 0x29, 0x2e,
	0xbb, 0x95, 0xf2, 0x1b, 0xfa, 0x0e, 0x11, 0x4b, 0x96, 0x51, 0x46, 0xa4, 0xc7, 0x82, 0x72, 0x21,
	0x03, 0xfb, 0xf0, 0xe1, 0x1f, 0x49, 0x29, 0xab, 0xe5, 0x47, 0x22, 0xab, 0x71, 0x5e, 0x31, 0xa1,
	0xbe, 0xa3, 0x83, 0x8f, 0xc4, 0x7c, 0x7c, 0xcd, 0x83, 0x17, 0xe7, 0xa1, 0x33, 0xca, 0x65, 0xac,
	0x71, 0x67, 0x68, 0xd9, 0x86, 0x46, 0xd0, 0x8c, 0xab, 0xb2, 0x8c, 0x8a, 0x9c, 0xd7, 0x21, 0x9f,
	0x24, 0x5f, 0xe5, 0xfc, 0x6a, 0x05, 0xe3, 0xd9, 0x0a, 0x16, 0x40, 0x40, 0x58, 0xe2, 0xf1, 0x54,
	0x0e, 0xfe, 0xf2, 0x80, 0x3d, 0x30, 0xf6, 0x3c, 0xad, 0xef, 0x27, 0xa1, 0xf9, 0xe3, 0xa2, 0xbf,
	0xf1, 0x31, 0x16, 0xc0, 0x6c, 0xb7, 0x11, 0xb5, 0x6b, 0x0f, 0x8c, 0x78, 0x9f, 0xd4, 0x12, 0x09,
	0x65, 0x0e, 0x39, 0x28, 0xdb, 0xcf, 0x58, 0x27, 0x07, 0xf3, 0xcf, 0x45, 0xcf, 0x8b, 0xfb, 0xfa,
	0xb7, 0xb6, 0xf9, 0xf9, 0x17, 0x8c, 0x99, 0x37, 0x47, 0x5d, 0x80, 0xc0, 0x75, 0xfc, 0x70, 0x15,
	0xcd, 0xbc, 0x79, 0x4f, 0x3b, 0x71, 0xd7, 0x57, 0x5c, 0x47, 0x23, 0x18, 0x38, 0xf6, 0x7a, 0xe9,
	0x2f, 0x5c, 0xdf, 0x0e, 0x03, 0x1b, 0x2f, 0xdc, 0x60, 0xad, 0x9e, 0x0c, 0xf4, 0x05, 0xda, 0x81,
	0xed, 0xcf, 0xbd, 0xc0, 0x51, 0x85, 0xc6, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xe8, 0xda,
	0xaa, 0x00, 0x03, 0x00, 0x00,
}
